-- Auto-generated by tools/build_info_assets.py from INFO.GGS.
-- Slot numbers match the put_sprite() literals in DISPLAY.CPP/ROBBO.CPP.
-- The HUD imagetable (images/info-table-16-19.png) is SLOT-INDEXED:
-- glyph for slot s is imagetable:getImage(s + 1) (1-based).

INFO_CELL_W = 16
INFO_CELL_H = 19

INFO = {
    digit0     = 17,   -- digit d = digit0 + d           (0x11)
    lifeEmpty  = 13, lifeFull = 14,
    keyEmpty   = 15, keyFull  = 16,
    sub1       = 28,   -- sub n(1..4) = sub1 + (n-1)      (0x1c)
    letterA    = 33,   -- group letter G = letterA + (G:byte()-65)  (0x21)
    iconScrews = 10, iconAmmo = 11, iconCave = 12,
}

-- Content width (px) of each glyph, for proportional advance.
INFO_GLYPH_W = {
    [10] = 10,
    [11] = 10,
    [12] = 11,
    [13] = 0,
    [14] = 14,
    [15] = 0,
    [16] = 13,
    [17] = 7,
    [18] = 2,
    [19] = 7,
    [20] = 7,
    [21] = 7,
    [22] = 7,
    [23] = 7,
    [24] = 7,
    [25] = 7,
    [26] = 7,
    [28] = 6,
    [29] = 7,
    [30] = 7,
    [31] = 7,
    [32] = 0,
    [33] = 7,
    [34] = 7,
    [35] = 6,
    [36] = 7,
    [37] = 7,
    [38] = 7,
    [39] = 7,
    [40] = 7,
    [41] = 4,
    [42] = 7,
    [43] = 7,
    [44] = 7,
    [45] = 7,
    [46] = 7,
    [47] = 7,
    [48] = 7,
    [49] = 7,
    [50] = 7,
    [51] = 7,
    [52] = 7,
    [53] = 7,
    [54] = 7,
    [55] = 7,
    [56] = 7,
    [57] = 6,
    [58] = 7,
}
