-- Sound engine, ported from ROBBO_C/RSOUNDS.CPP (+ RSOUNDS.H ids, DATA/FX.LST
-- priorities). The DOS samples (raw 8-bit unsigned PCM @ 8523 Hz) are converted
-- to WAV by tools/build_sounds.py into source/sounds/sfxNN.wav, with their
-- per-sound priority `level` baked into sound_data.lua (SOUND_LEVELS). NN is the
-- 1-based sound_table index, which equals the SFX id below (RSOUNDS.H enum).
--
-- The original drives ONE hardware channel through a 32-slot circular queue:
--   * level >= 99  (the spoken/voice samples): QUEUED so they never overlap.
--                  level == 100 would allow duplicates; 99 dedupes.
--   * level <  99  (short FX): played immediately, but ONLY if the queue is
--                  empty (a voice in progress suppresses them), and a new FX
--                  cuts off any FX still sounding (single channel).
-- We reproduce that exactly so the feel matches: voices play back-to-back,
-- effects are best-effort. play_queue() must be pumped once per sim step;
-- reset_queue() runs at each cave (re)start. (RSOUNDS.CPP SOUND/play_queue.)

import "CoreLibs/object"
import "sound_data"   -- SOUND_COUNT, SOUND_LEVELS (generated by build_sounds.py)

local sp <const> = playdate.sound.sampleplayer

-- SFX ids — verbatim from RSOUNDS.H `enum { KLIK=1, ... HMHMHM }`. Used as the
-- sound_table index (SOUND(num) -> sound_table[num-1]) so values are fixed.
SFX = {
    KLIK = 1, STRZAL = 2, BUM = 3, TELEPORT = 4, MAGNES = 5,
    STWUR_BUM = 6, ROBBO_BUM = 7, OCZY_PISK = 8, SRUBKA = 9, BATERIA = 10,
    KLUCZ = 11, KLUCZ_TRZA = 12, DRZWI_OPEN = 13, ZBIERZ_SRUBY = 14,
    ODSZUKAJ = 15, BRAWO = 16, BATERIA_LOW = 17, EXTRA_ROBO = 18, BIEDNY = 19,
    -- NEAR_SOUND ids for EXTRA reveals (objects.lua EXTRA_SOUNDS):
    N_SUPER = 20, N_NIES = 21, N_BAT = 22, N_KLUCZ = 23, N_SRUBA = 24,
    N_OKO = 25, N_BOMBA = 26, N_EXTRA = 27, N_HLE = 28, N_EXIT = 29, N_GUN = 30,
    -- Robbo's idle "humming" voice block (HMHMHM .. HMHMHM+11):
    HMHMHM = 31,
}

local players = {}     -- SFX id -> playdate.sound.sampleplayer (nil if not loaded)
local channel  = nil   -- the single "hardware channel": last sampleplayer played

-- 32-slot circular queue (RSOUNDS.CPP sq/qb/qe), 0-based to mirror the C.
local sq = {}
local qb, qe = 0, 0

function loadSounds()
    for i = 1, (SOUND_COUNT or 0) do
        local player = sp.new(string.format("sounds/sfx%02d", i))
        if player then players[i] = player end
    end
    resetQueue()
end

-- play_sample(): single-channel playback — a new sample cuts off whatever was
-- still sounding, exactly as the DOS one-buffer player does.
local function playSample(num)
    local player = players[num]
    if not player then return end
    if channel and channel:isPlaying() then channel:stop() end
    player:play()
    channel = player
end

-- sound_on(): is the channel still busy? (RSOUNDS.CPP uses the device's flag.)
local function soundOn()
    return channel ~= nil and channel:isPlaying()
end

-- SOUND(num): queue/play an effect — faithful port of RSOUNDS.CPP::SOUND().
function SOUND(num)
    if not num then return end
    local level = SOUND_LEVELS and SOUND_LEVELS[num]
    if level == nil then return end          -- unknown / not loaded: no-op
    if not players[num] then return end

    if level >= 99 then
        if qb == qe then                     -- queue empty: play now + enqueue
            playSample(num)
            sq[qe] = num
            qe = (qe == 31) and 0 or qe + 1
        else                                 -- queue busy: enqueue (dedupe < 100)
            local dup = false
            if level ~= 100 then
                for i = 0, 31 do
                    if sq[i] == num then dup = true break end
                end
            end
            if not dup then
                sq[qe] = num
                qe = (qe == 31) and 0 or qe + 1
            end
        end
    elseif qb == qe then                     -- short FX: only if no voice queued
        playSample(num)
    end
end

-- NEAR_SOUND(num): SOUND, gated to a window around Robbo (RSOUNDS.H macro). The
-- C does unsigned 16-bit word math; reproduce the &0xFFFF wrap so the asymmetric
-- [-5..+3] cols/rows window matches exactly. `current`/`robo` are cell indices.
function NEAR_SOUND(num, current, robo)
    local dx = ((current & 0x0f) - (robo & 0x0f) + 5) & 0xFFFF
    local dy = ((current >> 4)   - (robo >> 4)   + 5) & 0xFFFF
    if dx < 9 and dy < 9 then SOUND(num) end
end

-- play_queue(): advance the voice queue when the channel falls idle. Pump once
-- per sim step (RSOUNDS.CPP::play_queue, called from play()'s loop).
function playQueue()
    if (not soundOn()) and qb ~= qe then
        sq[qb] = 0
        qb = (qb == 31) and 0 or qb + 1
        if qb ~= qe then
            playSample(sq[qb])
        end
    end
end

-- reset_queue(): clear the queue at cave (re)start (RSOUNDS.CPP::reset_queue).
function resetQueue()
    qb, qe = 0, 0
    for i = 0, 31 do sq[i] = 0 end
end

------------------------------------------------------------------------------
-- Music (RSOUNDS.CPP load_song/play_song). The DOS .mus songs are pre-rendered
-- offline by tools/build_songs.py into one looping WAV each (music/<name>.wav),
-- reproducing load_song's pattern-slice-and-concatenate exactly; play_song()'s
-- next_sample loop becomes a looped sampleplayer (:play(0)). Songs play only on
-- menu/end screens, never during gameplay (the original lets the first cave SFX
-- cut the song off on the shared channel; we stop it explicitly on cave start).
--
-- Only ONE song is held in RAM at a time (each is ~2-2.6 MB): switching songs
-- releases the previous player. The "kodowa" code-entry song is dropped.
------------------------------------------------------------------------------
local musicPlayer = nil    -- the looping song sampleplayer (nil if none)
local currentSong = nil    -- name of the song currently loaded/playing

-- playSong(name): loop the named song. Idempotent — re-requesting the playing
-- song is a no-op (songs loop forever, so they never need restarting).
function playSong(name)
    if currentSong == name then return end
    stopSong()
    local p = sp.new("music/" .. name)
    if not p then return end
    musicPlayer = p
    currentSong = name
    p:play(0)              -- 0 == loop forever (play_song's next_sample loop)
end

-- stopSong(): stop music and release it (frees RAM for gameplay).
function stopSong()
    if musicPlayer then musicPlayer:stop() end
    musicPlayer = nil
    currentSong = nil
end
